
modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://github.com/HostaPlantain/Flora" #optional


[[mods]]

modId="flora"
version="0.2.0"
displayName="Flora Libs"

displayURL="https://github.com/HostaPlantain/Flora" #optional
logoFile="logo.png" #optional
credits="Hosta_Plantain" #optional
authors="Hosta_Plantain" #optional

description='''
Inside the Secret World of Plants
'''


[[dependencies.flora]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"
